project_id = "gmkgoymjuqyxlfsutaxa"

[functions.calculate-eda]
verify_jwt = false

[functions.train-models]
verify_jwt = false

[functions.predict]
verify_jwt = false

[functions.project-chat]
verify_jwt = false

[functions.delete-project]
verify_jwt = false

[functions.clear-project-chat]
verify_jwt = false

[functions.global-chat]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.run-scheduled-predictions]
verify_jwt = false

[functions.test-db-connection]
verify_jwt = false

[functions.test-cloud-connection]
verify_jwt = false

[functions.test-databricks-connection]
verify_jwt = false

[functions.ingest-database]
verify_jwt = false

[functions.ingest-cloud-data]
verify_jwt = false

[functions.ingest-databricks]
verify_jwt = false

[functions.parse-file]
verify_jwt = false

[functions.run-batch-predictions]
verify_jwt = false

[functions.process-export]
verify_jwt = false

[functions.process-import]
verify_jwt = false

[functions.calculate-dashboard-metrics]
verify_jwt = false
