project_id = "gmkgoymjuqyxlfsutaxa"

[functions.calculate-eda]
verify_jwt = false

[functions.train-models]
verify_jwt = false

[functions.predict]
verify_jwt = false

[functions.project-chat]
verify_jwt = false

[functions.delete-project]
verify_jwt = false

[functions.clear-project-chat]
verify_jwt = false

[functions.global-chat]
verify_jwt = false
